import { Application } from '@hotwired/stimulus';
import WSSlug from './controllers/ws-slug_controller';
import WSSelect from './controllers/ws-select_controller';
import WSDatePicker from './controllers/ws-date-picker_controller';
import WSInputMultiple from './controllers/ws-input-multiple_controller';
import WSColorPicker from './controllers/ws-color-picker_controller';
import WSRangeSlider from './controllers/ws-range-slider_controller';
import WSTooltip from './controllers/ws-tooltip_controller';
import WSDropdown from './controllers/ws-dropdown_controller';
import WSTableCollapse from './controllers/ws-table-collapse_controller';
import WSToggleChoice from './controllers/ws-toggle-choice_controller';
import WSCharacterCount from './controllers/ws-character-count_controller';
import WSSettings from './controllers/ws-settings_controller';

const stimulus = Application.start();
stimulus.register('ws-slug', WSSlug);
stimulus.register('ws-select', WSSelect);
stimulus.register('ws-datepicker', WSDatePicker);
stimulus.register('ws-input-multiple', WSInputMultiple);
stimulus.register('ws-color-picker', WSColorPicker);
stimulus.register('ws-range-slider', WSRangeSlider);
stimulus.register('ws-tooltip', WSTooltip);
stimulus.register('ws-dropdown', WSDropdown);
stimulus.register('ws-table-collapse', WSTableCollapse);
stimulus.register('ws-toggle-choice', WSToggleChoice);
stimulus.register('ws-character-count', WSCharacterCount);
stimulus.register('ws-settings', WSSettings);
