services:
    WS\Core\Library\Router\Router:
        decorates: router
        arguments: ['@.inner']
        calls:
            - [ setLoader, ['@WS\Core\Library\Router\RoutingLoader']]

    WS\Core\Library\Router\RoutingLoader:
        tags: [routing.loader]
        calls:
            - [ setProjectDir, ['%kernel.project_dir%']]
            - [ setLocalizationStrategy, ['@WS\Core\Library\Router\Loader\DefaultLocalizationStrategy']]
