parameters:
    storage.driver: 'local'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WS\Core\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Widget}'

    WS\Core\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    # Tag Services (WS Core Services must have 1024 priority)
    WS\Core\Service\SidebarDefinitionService:
        tags:
            - { name: ws.sidebar_definition, priority: 1024 }

    # Data Collector
    WS\Core\Library\DataCollector\BuildCollector:
        tags:
            - { name: data_collector, template: '@WSCore/data_collector/build.html.twig', id: 'ws.build_collector' }
