name: Unit Testing

on:
  pull_request:
    # aquí debemos seleccionar las ramas donde queremos ejecutar este linter
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # aquí añadir las versiones de PHP sobre las que se ha de lanzar el job
        php-version: [ '7.4' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Composer install
        uses: php-actions/composer@v5
        with:
          command: install
          args: --ignore-platform-reqs --no-scripts
          version: 2
          php_version: ${{ matrix.php-version }}

      - name: PHP Unit Testing
        uses: php-actions/phpunit@v2
        with:
          args: tests/Unit/
          configuration: phpunit.xml.dist
          bootstrap: vendor/autoload.php
          version: 9.5
          php_version: ${{ matrix.php-version }}
